---
- name: "Pull solr image"
  docker_image:
    name: "{{ solr.image }}"
    source: pull
  tags:
    - install

- name: Prepare folders
  file: path="{{ item.path }}" state=directory mode="{{ item.mode }}" owner="{{ item.owner }}"
  with_items:
    - { "path": "/var/log/docker", "owner": "root", "mode": "0755" }
    - {
        "path": "/var/log/docker/solr",
        "owner": "root",
        "mode": "0777",
      }

# - name: Make directories for solr
#   file:
#     path: "{{ item.dest }}"
#     state: "{{ item.state }}"
#     mode: "0755"
#     owner: "{{ user_name }}"
#     group: "{{ user_primary_group }}"
#   with_items:
#     - state: directory
#       dest: /etc/victoriametrics

# - name: solr | Send config files
#   copy:
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: 0644
#     owner: "{{ user_name }}"
#     group: "{{ user_primary_group }}"
#   with_items:
#     - src: files/local-config.yml
#       dest: /etc/victoriametrics/local-config.yml

- name: "Install Systemd service for solr"
  template:
    src: docker_service_unit.j2
    dest: "/etc/systemd/system/solr.service"
    owner: root
    group: root
    mode: "0644"
  tags:
    - install

- name: Reread systemd configs
  systemd:
    daemon_reload: yes
  tags:
    - install

- name: "Enable and start solr service"
  systemd:
    name: "solr"
    enabled: yes
    state: restarted
  tags:
    - enable
    - install
