// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: sms_provider_service.proto

package sms_service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ShipperId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipperId string `protobuf:"bytes,1,opt,name=shipper_id,json=shipperId,proto3" json:"shipper_id,omitempty"`
}

func (x *ShipperId) Reset() {
	*x = ShipperId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sms_provider_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShipperId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipperId) ProtoMessage() {}

func (x *ShipperId) ProtoReflect() protoreflect.Message {
	mi := &file_sms_provider_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipperId.ProtoReflect.Descriptor instead.
func (*ShipperId) Descriptor() ([]byte, []int) {
	return file_sms_provider_service_proto_rawDescGZIP(), []int{0}
}

func (x *ShipperId) GetShipperId() string {
	if x != nil {
		return x.ShipperId
	}
	return ""
}

var File_sms_provider_service_proto protoreflect.FileDescriptor

var file_sms_provider_service_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x6d, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65,
	0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x12, 0x73, 0x6d, 0x73, 0x5f, 0x70, 0x72, 0x6f, 0x76,
	0x69, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2a, 0x0a, 0x09, 0x53, 0x68, 0x69, 0x70, 0x70,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65,
	0x72, 0x49, 0x64, 0x32, 0xbd, 0x01, 0x0a, 0x12, 0x53, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x64, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33, 0x0a, 0x03, 0x47, 0x65,
	0x74, 0x12, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x68, 0x69,
	0x70, 0x70, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x53, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x00, 0x12,
	0x39, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x15, 0x2e, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x6d, 0x73, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x06, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x49, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x22, 0x00, 0x42, 0x16, 0x5a, 0x14, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x73, 0x6d, 0x73, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sms_provider_service_proto_rawDescOnce sync.Once
	file_sms_provider_service_proto_rawDescData = file_sms_provider_service_proto_rawDesc
)

func file_sms_provider_service_proto_rawDescGZIP() []byte {
	file_sms_provider_service_proto_rawDescOnce.Do(func() {
		file_sms_provider_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_sms_provider_service_proto_rawDescData)
	})
	return file_sms_provider_service_proto_rawDescData
}

var file_sms_provider_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sms_provider_service_proto_goTypes = []interface{}{
	(*ShipperId)(nil),   // 0: genproto.ShipperId
	(*SmsProvider)(nil), // 1: genproto.SmsProvider
	(*empty.Empty)(nil), // 2: google.protobuf.Empty
}
var file_sms_provider_service_proto_depIdxs = []int32{
	0, // 0: genproto.SmsProviderService.Get:input_type -> genproto.ShipperId
	1, // 1: genproto.SmsProviderService.Create:input_type -> genproto.SmsProvider
	0, // 2: genproto.SmsProviderService.Delete:input_type -> genproto.ShipperId
	1, // 3: genproto.SmsProviderService.Get:output_type -> genproto.SmsProvider
	2, // 4: genproto.SmsProviderService.Create:output_type -> google.protobuf.Empty
	2, // 5: genproto.SmsProviderService.Delete:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sms_provider_service_proto_init() }
func file_sms_provider_service_proto_init() {
	if File_sms_provider_service_proto != nil {
		return
	}
	file_sms_provider_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_sms_provider_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShipperId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sms_provider_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sms_provider_service_proto_goTypes,
		DependencyIndexes: file_sms_provider_service_proto_depIdxs,
		MessageInfos:      file_sms_provider_service_proto_msgTypes,
	}.Build()
	File_sms_provider_service_proto = out.File
	file_sms_provider_service_proto_rawDesc = nil
	file_sms_provider_service_proto_goTypes = nil
	file_sms_provider_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SmsProviderServiceClient is the client API for SmsProviderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmsProviderServiceClient interface {
	Get(ctx context.Context, in *ShipperId, opts ...grpc.CallOption) (*SmsProvider, error)
	Create(ctx context.Context, in *SmsProvider, opts ...grpc.CallOption) (*empty.Empty, error)
	Delete(ctx context.Context, in *ShipperId, opts ...grpc.CallOption) (*empty.Empty, error)
}

type smsProviderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSmsProviderServiceClient(cc grpc.ClientConnInterface) SmsProviderServiceClient {
	return &smsProviderServiceClient{cc}
}

func (c *smsProviderServiceClient) Get(ctx context.Context, in *ShipperId, opts ...grpc.CallOption) (*SmsProvider, error) {
	out := new(SmsProvider)
	err := c.cc.Invoke(ctx, "/genproto.SmsProviderService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsProviderServiceClient) Create(ctx context.Context, in *SmsProvider, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.SmsProviderService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *smsProviderServiceClient) Delete(ctx context.Context, in *ShipperId, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.SmsProviderService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmsProviderServiceServer is the server API for SmsProviderService service.
type SmsProviderServiceServer interface {
	Get(context.Context, *ShipperId) (*SmsProvider, error)
	Create(context.Context, *SmsProvider) (*empty.Empty, error)
	Delete(context.Context, *ShipperId) (*empty.Empty, error)
}

// UnimplementedSmsProviderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSmsProviderServiceServer struct {
}

func (*UnimplementedSmsProviderServiceServer) Get(context.Context, *ShipperId) (*SmsProvider, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedSmsProviderServiceServer) Create(context.Context, *SmsProvider) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedSmsProviderServiceServer) Delete(context.Context, *ShipperId) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}

func RegisterSmsProviderServiceServer(s *grpc.Server, srv SmsProviderServiceServer) {
	s.RegisterService(&_SmsProviderService_serviceDesc, srv)
}

func _SmsProviderService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipperId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsProviderServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.SmsProviderService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsProviderServiceServer).Get(ctx, req.(*ShipperId))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsProviderService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SmsProvider)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsProviderServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.SmsProviderService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsProviderServiceServer).Create(ctx, req.(*SmsProvider))
	}
	return interceptor(ctx, in, info, handler)
}

func _SmsProviderService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShipperId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmsProviderServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.SmsProviderService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmsProviderServiceServer).Delete(ctx, req.(*ShipperId))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmsProviderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.SmsProviderService",
	HandlerType: (*SmsProviderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _SmsProviderService_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _SmsProviderService_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SmsProviderService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms_provider_service.proto",
}
