- name: Run apt-get update
  apt:
    update_cache: yes

- name: Install HAProxy
  apt:
    name: haproxy
    state: present

- name: Copy HAProxy configuration from template
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: Restart HAProxy

