---
- name: "Pull codeserver image"
  docker_image:
    name: "{{ codeserver.image }}"
    source: pull
  tags:
    - install

- name: Prepare folders
  file: path="{{ item.path }}" state=directory mode="{{ item.mode }}" owner="{{ item.owner }}"
  with_items:
    - { "path": "/var/log/docker", "owner": "root", "mode": "0755" }
    - {
        "path": "/var/log/docker/codeserver",
        "owner": "root",
        "mode": "0777",
      }

- name: "Install Systemd service for cloudwatch-exporter"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - src: docker_service_unit.j2
      dest: /etc/systemd/system/codeserver.service
  tags:
    - install

- name: Reread systemd configs
  systemd:
    daemon_reload: yes
  tags:
    - install

- name: "Enable and start codeserver service"
  systemd:
    name: "codeserver"
    enabled: yes
    state: restarted
  tags:
    - enable
    - install
