// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: menu_service.proto

package catalog_service

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetMenuImageRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShipperId string `protobuf:"bytes,1,opt,name=shipper_id,json=shipperId,proto3" json:"shipper_id,omitempty"`
}

func (x *GetMenuImageRequest) Reset() {
	*x = GetMenuImageRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_menu_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMenuImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuImageRequest) ProtoMessage() {}

func (x *GetMenuImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuImageRequest.ProtoReflect.Descriptor instead.
func (*GetMenuImageRequest) Descriptor() ([]byte, []int) {
	return file_menu_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetMenuImageRequest) GetShipperId() string {
	if x != nil {
		return x.ShipperId
	}
	return ""
}

var File_menu_service_proto protoreflect.FileDescriptor

var file_menu_service_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x65, 0x6e, 0x75, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x65, 0x6e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0a, 0x6d, 0x65, 0x6e,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x34, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4d, 0x65,
	0x6e, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x68, 0x69, 0x70, 0x70, 0x65, 0x72, 0x49, 0x64, 0x32, 0x88, 0x01,
	0x0a, 0x10, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x3b, 0x0a, 0x03, 0x47, 0x65, 0x74, 0x12, 0x1d, 0x2e, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6d, 0x61, 0x67,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x22, 0x00, 0x12,
	0x37, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4d, 0x65, 0x6e, 0x75, 0x49, 0x6d, 0x61, 0x67, 0x65, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x1a, 0x5a, 0x18, 0x67, 0x65, 0x6e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_menu_service_proto_rawDescOnce sync.Once
	file_menu_service_proto_rawDescData = file_menu_service_proto_rawDesc
)

func file_menu_service_proto_rawDescGZIP() []byte {
	file_menu_service_proto_rawDescOnce.Do(func() {
		file_menu_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_menu_service_proto_rawDescData)
	})
	return file_menu_service_proto_rawDescData
}

var file_menu_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_menu_service_proto_goTypes = []interface{}{
	(*GetMenuImageRequest)(nil), // 0: genproto.GetMenuImageRequest
	(*MenuImage)(nil),           // 1: genproto.MenuImage
	(*empty.Empty)(nil),         // 2: google.protobuf.Empty
}
var file_menu_service_proto_depIdxs = []int32{
	0, // 0: genproto.MenuImageService.Get:input_type -> genproto.GetMenuImageRequest
	1, // 1: genproto.MenuImageService.Update:input_type -> genproto.MenuImage
	1, // 2: genproto.MenuImageService.Get:output_type -> genproto.MenuImage
	2, // 3: genproto.MenuImageService.Update:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_menu_service_proto_init() }
func file_menu_service_proto_init() {
	if File_menu_service_proto != nil {
		return
	}
	file_menu_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_menu_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetMenuImageRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_menu_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_service_proto_goTypes,
		DependencyIndexes: file_menu_service_proto_depIdxs,
		MessageInfos:      file_menu_service_proto_msgTypes,
	}.Build()
	File_menu_service_proto = out.File
	file_menu_service_proto_rawDesc = nil
	file_menu_service_proto_goTypes = nil
	file_menu_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MenuImageServiceClient is the client API for MenuImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MenuImageServiceClient interface {
	Get(ctx context.Context, in *GetMenuImageRequest, opts ...grpc.CallOption) (*MenuImage, error)
	Update(ctx context.Context, in *MenuImage, opts ...grpc.CallOption) (*empty.Empty, error)
}

type menuImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMenuImageServiceClient(cc grpc.ClientConnInterface) MenuImageServiceClient {
	return &menuImageServiceClient{cc}
}

func (c *menuImageServiceClient) Get(ctx context.Context, in *GetMenuImageRequest, opts ...grpc.CallOption) (*MenuImage, error) {
	out := new(MenuImage)
	err := c.cc.Invoke(ctx, "/genproto.MenuImageService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *menuImageServiceClient) Update(ctx context.Context, in *MenuImage, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/genproto.MenuImageService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MenuImageServiceServer is the server API for MenuImageService service.
type MenuImageServiceServer interface {
	Get(context.Context, *GetMenuImageRequest) (*MenuImage, error)
	Update(context.Context, *MenuImage) (*empty.Empty, error)
}

// UnimplementedMenuImageServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMenuImageServiceServer struct {
}

func (*UnimplementedMenuImageServiceServer) Get(context.Context, *GetMenuImageRequest) (*MenuImage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedMenuImageServiceServer) Update(context.Context, *MenuImage) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}

func RegisterMenuImageServiceServer(s *grpc.Server, srv MenuImageServiceServer) {
	s.RegisterService(&_MenuImageService_serviceDesc, srv)
}

func _MenuImageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMenuImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuImageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.MenuImageService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuImageServiceServer).Get(ctx, req.(*GetMenuImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MenuImageService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MenuImage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MenuImageServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/genproto.MenuImageService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MenuImageServiceServer).Update(ctx, req.(*MenuImage))
	}
	return interceptor(ctx, in, info, handler)
}

var _MenuImageService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "genproto.MenuImageService",
	HandlerType: (*MenuImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MenuImageService_Get_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _MenuImageService_Update_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "menu_service.proto",
}
