apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db/db-config.yaml
  - db/db-depl.yaml
  - db/db-service.yaml
  - massage-broker/rabbitmq-config.yaml
  - massage-broker/rabbitmq-depl.yaml
  - massage-broker/rabbitmq-service.yaml
  - nginx/nginx-depl.yaml
  - nginx/nginx-service.yaml

# run this file
# kustomize build installition.yml | kubectl apply -f -
---
# with another option create kustomization.yaml file each directory db massage-broker nginx
# kustomization.yaml for db directory
apiVersion: kustomization.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - db-config.yaml
  - db-depl.yaml
  - db-service.yaml
---
# kustomization file for massage-broker
apiVersion: kustomization.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rabbitmq-config.yaml
  - rabbitmq-depl.yaml
  - rabbitmq-service.yaml
---
# kustomization file for nginx directory
apiVersion: kustomization.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-depl.yaml
  - nginx-service.yaml

images:
  - name: gcr.io/
    newTag: 1.0
    newName: