# roles/cilium_hubble/tasks/main.yml

---
- ansible.builtin.shell:
    cmd: helm repo add cilium https://helm.cilium.io/
  args:
    executable: /bin/bash

- ansible.builtin.shell:
    cmd: helm install cilium cilium/cilium --version 1.14.6 --namespace kube-system
  args:
    executable: /bin/bash

- ansible.builtin.shell:
    cmd: helm upgrade cilium cilium/cilium --version 1.14.6 --namespace kube-system --reuse-values --set hubble.relay.enabled=true --set hubble.ui.enabled=true
  args:
    executable: /bin/bash

- ansible.builtin.shell:
    cmd: cilium hubble port-forward&
  args:
    executable: /bin/bash

- ansible.builtin.copy:
    src: hubble.sh
    dest: /root/hubble.sh
    mode: '0755'

- ansible.builtin.shell:
    cmd: /root/hubble.sh
  args:
    executable: /bin/bash



