variables:
  IMAGE_NAME: bexruzdev/micro
  IMAGE_TAG: $CI_PIPELINE_IID

stages:
  - build
  - migrate
  - deploy

services:
  - docker:dind


job_build:
  stage: build
  tags:
    - golang6
  image: docker:dind

  before_script:
    - cat $KUBECONFIG
    - whoami
    - docker login --username "bexruzdev" --password "bexruzffakk"

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG


job_migrate:
  stage: migrate
  tags:
    - golang6
  before_script:
    - apk add wget && wget https://github.com/golang-migrate/migrate/releases/download/v4.14.1/migrate.linux-amd64.tar.gz
    - tar -xvf migrate.linux-amd64.tar.gz && mv migrate.linux-amd64 migrate && chmod +x migrate
  script:
    - ./migrate -path=/home/bexruz/test7777/test_microservice-master/migrations -database="${FAST_GO_SMS_SERVICE}?sslmode=disable&connect_timeout=0&x-migrations-table=migrations_admin" up



job_deploy:
  stage: deploy
  image: docker:dind

  tags:
    - golang6

  before_script:
    - apk --no-cache add curl
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl
    - mv kubectl /usr/local/bin/
  script:
    - mkdir  /root/.kube
    - cat $KUBECONFIG > /root/.kube/config
    - docker login --username "bexruzdev" --password "bexruzffakk"
    - docker pull $IMAGE_NAME:$IMAGE_TAG
    - kubectl set image deployment/my-golang-deployment my-golang=$IMAGE_NAME:$IMAGE_TAG
