- name: Add Grafana APT repository key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana APT repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana

- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Grafana
  ansible.builtin.apt:
    name: grafana
    state: present

- name: Start Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started

- name: Enable Grafana service
  ansible.builtin.systemd:
    name: grafana-server
    enabled: yes

- name: Update APT package cache
  ansible.builtin.apt:
    update_cache: yes

- name: Create prometheus group
  ansible.builtin.command:
    cmd: "groupadd --system prometheus"

- name: Create prometheus group
  ansible.builtin.command:
    cmd: "useradd -s /sbin/nologin --system -g prometheus prometheus"

- name: Creates directory prometheus
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory

- name: Creates directory prometheus
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory

- name: Download Prometheus binary release
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz"
    dest: "/root/prometheus-2.43.0.linux-amd64.tar.gz"

- name: Creates directory prometheus
  ansible.builtin.file:
    path: /root/prometheus
    state: directory

- name: Extract Prometheus tarball
  ansible.builtin.shell:
    cmd: "tar vxf /root/prometheus-2.43.0.linux-amd64.tar.gz -C /root/prometheus --strip-components=1"

- name: Move Prometheus binary
  ansible.builtin.command:
    cmd: "mv prometheus/prometheus /usr/local/bin"

- name: Move Prometheus binary
  ansible.builtin.command:
    cmd: "mv prometheus/promtool /usr/local/bin"

- name: Change ownership of prometheus binary
  ansible.builtin.command:
    cmd: "sudo chown prometheus:prometheus /usr/local/bin/prometheus"

- name: Change ownership of promtool binary
  ansible.builtin.command:
    cmd: "sudo chown prometheus:prometheus /usr/local/bin/promtool"

- name: Move consoles directory
  ansible.builtin.command:
    cmd: "sudo mv prometheus/consoles /etc/prometheus"

- name: Move console_libraries directory
  ansible.builtin.command:
    cmd: "sudo mv prometheus/console_libraries /etc/prometheus"

- name: Move prometheus.yml file
  ansible.builtin.command:
    cmd: "sudo mv prometheus/prometheus.yml /etc/prometheus"

- name: Change ownership of /etc/prometheus directory
  ansible.builtin.command:
    cmd: "sudo chown prometheus:prometheus /etc/prometheus"

- name: Change ownership of /etc/prometheus/consoles directory
  ansible.builtin.command:
    cmd: "sudo chown -R prometheus:prometheus /etc/prometheus/consoles"

- name: Change ownership of /etc/prometheus/console_libraries directory
  ansible.builtin.command:
    cmd: "sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries"

- name: Change ownership of /var/lib/prometheus directory
  ansible.builtin.command:
    cmd: "sudo chown -R prometheus:prometheus /var/lib/prometheus"

- name: Create Prometheus systemd service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Prometheus
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
          --config.file /etc/prometheus/prometheus.yml \
          --storage.tsdb.path /var/lib/prometheus/ \
          --web.console.templates=/etc/prometheus/consoles \
          --web.console.libraries=/etc/prometheus/console_libraries

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service

- name: Reload systemd
  ansible.builtin.systemd:
    name: prometheus
    state: reloaded

- name: Start Prometheus service
  ansible.builtin.systemd:
    name: prometheus
    state: started

- name: Download Node Exporter binary
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter-1.3.1.linux-amd64.tar.gz"

- name: Extract Node Exporter
  ansible.builtin.unarchive:
    src: "/tmp/node_exporter-1.3.1.linux-amd64.tar.gz"
    dest: "/tmp"
    remote_src: yes

- name: Copy Node Exporter binary
  ansible.builtin.copy:
    src: "/tmp/node_exporter-1.3.1.linux-amd64/node_exporter"
    dest: "/usr/local/bin/"
    mode: 0755

- name: Create node_exporter user
  ansible.builtin.user:
    name: node_exporter
    shell: /bin/false
    system: yes

- name: Change ownership of Node Exporter binary
  ansible.builtin.file:
    path: "/usr/local/bin/node_exporter"
    owner: node_exporter
    group: node_exporter
    mode: 0755

- name: Create Node Exporter systemd service file
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Node Exporter
      After=network.target

      [Service]
      User=node_exporter
      Group=node_exporter
      Type=simple
      ExecStart=/usr/local/bin/node_exporter

      [Install]
      WantedBy=multi-user.target
    dest: "/etc/systemd/system/node_exporter.service"

- name: Reload systemd
  ansible.builtin.systemd:
    name: node_exporter
    state: reloaded

- name: Start Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    state: started

- name: Enable Node Exporter service
  ansible.builtin.systemd:
    name: node_exporter
    enabled: yes

- name: Add scrape_configs for node_exporter
  ansible.builtin.lineinfile:
    path: "/etc/prometheus/prometheus.yml"
    insertafter: EOF
    line: |
      #
      - job_name: 'node_exporter'
        static_configs:
          - targets: ['localhost:9100']
  notify: Reload Prometheus

