---
certbot_package: certbot
# Certbot auto-renew cron job configuration (for certificate renewals).
certbot_auto_renew: true
# auto_renew_user: "root"
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_options: "--quiet --no-self-upgrade"

certbot_auto_renew_day: "1"
certbot_auto_renew_hour: "18"
certbot_auto_renew_minute: "00"