---
# aWV0M3NvaHIzb29qM29oZ2gmaW9jYWVn
users_root_password_hash: '$2y$10$7AqjqSFtG1r3uHBk494yzuQ80K1kijlTftYYoJ3LyW/S1.Kyk4mcW'

users_default_shell: /bin/zsh
users_create_home_dirs: true
users_home_directory: "/home"

users_list: []
users_list_basic:
  - name: developer
    comment: 'Universal dev user'
    groups: [ ]
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX46T2FnM/YS3bkZTIK9vysA44PeHjOZcODMnkyusA+YZAxXA39tbkMbx12nulTrY4obVnFo19rDC879YX7KIi/zDBQs0WjrfDZE+FyUWUjlnKqQ4uMsyhiQy0rmuJ75RaAxbDDd14wJhYhaY8rQ1NWpGSIveHZGnwCL+b7v2fxo5FD4Fyde4RsrUQeEq3PEteiaV20uaYDTjs3pWtTMB3dbBwMZwx1C9IdA6hTxj579LmSesbRkummeK623IBOfJ/lujTY0jDZSHndPNxxMQAVoxV6fl1O/UETrSzhQfI4aqjV9zhtAwtcnxLs4L1bzEZir1JiqPjv3mZzagZ5jVnzOAWPDBacSzjQkYLCS4/viINtKp8F1MnvlvvkIUX2BNKVjEjABVXTU5cdVYUk06Sg4lDHkM843Op1c4Njnmo2MQBxyTMKPvlTIuh2yUR3Tk2iGUud3r9H92a9cOXL5FXb1/vRjLNzaflVfHNuYUQkdC9pHPsSmgsDdIz1ab1JRM= jamshidyerzakov@Jamshids-MBP"
  - name: ubuntu
    comment: 'Universal super user'
    groups: [ sudo ]
    ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDX46T2FnM/YS3bkZTIK9vysA44PeHjOZcODMnkyusA+YZAxXA39tbkMbx12nulTrY4obVnFo19rDC879YX7KIi/zDBQs0WjrfDZE+FyUWUjlnKqQ4uMsyhiQy0rmuJ75RaAxbDDd14wJhYhaY8rQ1NWpGSIveHZGnwCL+b7v2fxo5FD4Fyde4RsrUQeEq3PEteiaV20uaYDTjs3pWtTMB3dbBwMZwx1C9IdA6hTxj579LmSesbRkummeK623IBOfJ/lujTY0jDZSHndPNxxMQAVoxV6fl1O/UETrSzhQfI4aqjV9zhtAwtcnxLs4L1bzEZir1JiqPjv3mZzagZ5jVnzOAWPDBacSzjQkYLCS4/viINtKp8F1MnvlvvkIUX2BNKVjEjABVXTU5cdVYUk06Sg4lDHkM843Op1c4Njnmo2MQBxyTMKPvlTIuh2yUR3Tk2iGUud3r9H92a9cOXL5FXb1/vRjLNzaflVfHNuYUQkdC9pHPsSmgsDdIz1ab1JRM= jamshidyerzakov@Jamshids-MBP"


# - name: "{{ lookup('hashi_vault', 'secret=secret/data/project-credentials/{{ inventory_hostname }}:username')}}"
#   password: "{{ lookup('hashi_vault', 'secret=secret/data/project-credentials/{{ inventory_hostname }}:pass')}}"
#   primary_group: "{{ lookup('hashi_vault', 'secret=secret/data/project-credentials/{{ inventory_hostname }}:username')}}"
 