---
- name: Add Jetstack Helm Repository
  ansible.builtin.shell:
    cmd: helm repo add jetstack https://charts.jetstack.io

- name: Update Helm Repositories
  ansible.builtin.shell:
    cmd: helm repo update

- name: Run Helm Show Values Command
  ansible.builtin.shell:
    cmd: helm show values jetstack/cert-manager --version v1.13.2 > /root/valuess.yml 
  args:
    executable: /bin/bash

- name: Open values.yml and modify installCRDs and prometheus settings
  ansible.builtin.replace:
    path: /root/valuess.yml
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: 'installCRDs: false', replace: 'installCRDs: true' }
    - { regexp: '^prometheus:\n *enabled: true', replace: 'prometheus:\n  enabled: false' }

- name: Run Helm Upgrade Command
  ansible.builtin.shell:
    cmd: helm upgrade cert-manager jetstack/cert-manager --install --create-namespace --namespace cert-manager --version v1.13.2 --values /root/valuess.yml #--set installCRDs=false --set prometheus.enabled=false #--values ./values.yml
  args:
    executable: /bin/bash

- name: Create a file
  file:
    path: /root/issuer.yml
    state: touch

- name: Create Issuer YAML File
  ansible.builtin.blockinfile:
    path: /root/issuer.yml
    block: |
      apiVersion: cert-manager.io/v1
      kind: Issuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          server: https://acme-v02.api.letsencrypt.org/directory
          email: bexruzffakk02@gmail.com
          privateKeySecretRef:
            name: letsencrypt-prod
          solvers:
            - http01:
                ingress:
                  ingressClassName: nginx
    marker: "# {mark} ANSIBLE MANAGED BLOCK"

- name: Apply Issuer Configuration
  ansible.builtin.command:
    cmd: kubectl apply -f /root/issuer.yml
  args:
    executable: /bin/bash

- name: Create a file
  file:
    path: /root/example.yml
    state: touch

- name: Create example.yml
  ansible.builtin.copy:
    dest: /root/example.yml
    content: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: example-pods
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx-container
            image: nginx:latest
            ports:
              - containerPort: 80

      ---
      apiVersion: v1
      kind: Service
      metadata:
        name: example-service
      spec:
        selector:
          app: nginx
        ports:
          - protocol: TCP
            port: 80
            targetPort: 80

      ---
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: example-ingress
        annotations:
          cert-manager.io/issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
      spec:
        ingressClassName: nginx
        rules:
          - host: test.bexruzdev.uz
            http:
              paths:
                - path: /
                  pathType: Prefix
                  backend:
                    service:
                      name: example-service
                      port:
                        number: 80
        tls:
          - secretName: sll-test-bexruzdev-uz
            hosts:
              - test.bexruzdev.uz

- name: Deploy example file to k8s
  ansible.builtin.shell:
    cmd: kubectl apply -f /root/example.yml

