apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
replicas:
- name: nginx-deployment
  count: 1
images:
- name: nginx
  newName: alpine
  newTag: 3.6

patches:
  - target:
      kind: Service
      name: nginx-service
    patch: |
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30081

  - target:
      kind: Pod
      name: mypod
    patch: |
      - op: replace
        path: /spec/containers/0/image
        value: busybox:latest

