version: '3'
volumes:
  mymongo-db:
    driver: local

networks:
  for-docker:
    name: for-docker
    driver: bridge
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - for-docker
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mymongo-db:/data/db

  mongo-express:
    image: mongo-express 
    container_name: mongo-express
    ports: 
      - "8081:8081"
    networks:
      - for-docker
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
      - ME_CONFIG_MONGODB_SERVER=mongodb
    restart: always

