victoria-metrics-operator:
  enabled: {{ kubernetes_monitoring_victoria_operator_enabled }}
  nodeSelector:
    {{ kubernetes_monitoring_node_label }}: "true"

  # -- Tells helm to remove CRD after chart remove
  cleanupCRD: true
  cleanupImage:
    repository: gcr.io/google_containers/hyperkube
    tag: v1.18.0
    pullPolicy: IfNotPresent

  createCRD: false # we disable crd creation by operator chart as we create them in this chart
  operator:
    # -- By default, operator converts prometheus-operator objects.
    disable_prometheus_converter: true