apiVersion: apps/v1
kind: Deployment
metadata:
  name: udevs-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udevs-postgres
  template:
    metadata:
      labels:
        app: udevs-postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: postgres
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: udevs-postgres-service
spec:
  selector:
    app: udevs-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP

