students:
  - name: abdulaziz
    port: 8801
    pass: eifeV7en
  - name: fazliddin
    port: 8802
    pass: OojuFae1
  - name: feruz
    port: 8803
    pass: fowie2Ee
  - name: shakhzod
    port: 8804
    pass: Yeeyain2
  - name: sanjar
    port: 8805
    pass: Eith1noo
  - name: sherzod
    port: 8806
    pass: Ra0Lequ2
  - name: ravshan
    port: 8807
    pass: bohp9Ee5
  - name: nuriddin
    port: 8808
    pass: xie9Ahnu
  - name: xurshid
    port: 8809
    pass: Oi0ieQue
