# Use the official Python image as a base image
FROM python:3.9

# Set the working directory in the container
RUN pip install aiogram==2.25.1

RUN pip install datetime requests
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app/


# Command to run your application
CMD [ "python", "main.py" ]