apiVersion: v1
kind: Namespace
metadata:
  name: test77

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test777
  namespace: test77
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods-global
subjects:
- kind: ServiceAccount
  name: test777
  namespace: test77
roleRef:
  kind: ClusterRole
  name: pod-reader


#sudo kubectl auth can-i create pods --as=system:serviceaccount:test77:test777
