{
 "title": "Common",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "CPU | Shipox Prod Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Shipox-Prod-App1",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App1\",job=\"shipox_prod_app\", mode!=\"idle\"}[1m0s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App1\",job=\"shipox_prod_app\"}[1m0s])))) * 100"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App2",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App2\",job=\"shipox_prod_app\", mode!=\"idle\"}[1m0s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App2\",job=\"shipox_prod_app\"}[1m0s])))) * 100"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App3",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App3\",job=\"shipox_prod_app\", mode!=\"idle\"}[1m0s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App3\",job=\"shipox_prod_app\"}[1m0s])))) * 100"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App4",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App4\",job=\"shipox_prod_app\", mode!=\"idle\"}[1m0s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App4\",job=\"shipox_prod_app\"}[1m0s])))) * 100"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App5",
   "type": "gauge",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by(instance) (irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App5\",job=\"shipox_prod_app\", mode!=\"idle\"}[1m0s])) / on(instance) group_left sum by (instance)((irate(node_cpu_seconds_total{instance=\"Shipox-Prod-App5\",job=\"shipox_prod_app\"}[1m0s])))) * 100"
    }
   ]
  },
  { "title": "RAM | Shipox Prod Apps", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Shipox-Prod-App1",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"Shipox-Prod-App1\",job=\"shipox_prod_app\"} * 100) / node_memory_MemTotal_bytes{instance=\"Shipox-Prod-App1\",job=\"shipox_prod_app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App2",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"Shipox-Prod-App2\",job=\"shipox_prod_app\"} * 100) / node_memory_MemTotal_bytes{instance=\"Shipox-Prod-App2\",job=\"shipox_prod_app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App3",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"Shipox-Prod-App3\",job=\"shipox_prod_app\"} * 100) / node_memory_MemTotal_bytes{instance=\"Shipox-Prod-App3\",job=\"shipox_prod_app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App4",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"Shipox-Prod-App4\",job=\"shipox_prod_app\"} * 100) / node_memory_MemTotal_bytes{instance=\"Shipox-Prod-App4\",job=\"shipox_prod_app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Shipox-Prod-App5",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"Shipox-Prod-App5\",job=\"shipox_prod_app\"} * 100) / node_memory_MemTotal_bytes{instance=\"Shipox-Prod-App5\",job=\"shipox_prod_app\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}