---
- name: Loki | Send template file
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: "{{ user_name }}"
    group: "{{ user_primary_group }}"
  with_items:
    - src: templates/local-config.yml.j2
      dest: /home/{{ user_name }}/tmp/local-config.yml

- name: Loki | Docker compose up
  docker_stack:
    state: present
    name: "{{ stack_name }}"
    compose:
      - version: "3.7"
        services:
          loki:
            image: "grafana/loki:{{ loki.version }}"
            volumes:
              - /home/{{ user_name }}/tmp/local-config.yml:/etc/loki/local-config.yml
            ports:
              - "{{ loki.external_port }}:3100"
            command: -config.file=/etc/loki/local-config.yml
