STACK={{ stack_name }}
service-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c services/docker-compose.yml ${STACK}

vault-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c vault/vault.yml ${STACK}

vault-agent-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c vault/vault-agent.yml ${STACK}

minio-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c minio/minio.yml ${STACK}

mongo-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c mongo/mongo.yml ${STACK}

rmq-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c rmq/rmq.yml ${STACK}

redis-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c redis/redis.yml ${STACK}

kafka-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c kafka/kafka.yml ${STACK}

mon-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c monitoring/docker-compose.yml ${STACK}

alert-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c alert/docker-compose.yml ${STACK}

ne-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c monitoring/docker-compose.ne.yml ${STACK}

pe-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c monitoring/docker-compose.pe.yml ${STACK}

promtail-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c monitoring/docker-compose.promtail.yml ${STACK}

loki-up:
	set -a &&. ./.env && set +a && docker stack deploy --with-registry-auth -c monitoring/docker-compose.loki.yml ${STACK}
