- name: Install Zsh
  apt:
    name: zsh
    state: present

- name: Change user shell to Zsh
  user:
    name: root
    shell: /usr/bin/zsh

- name: Install Git
  apt:
    name: git
    state: present

- name: Install Oh-My-Zsh
  shell: >
    sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

- name: Install autosuggestions
  shell: >
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

- name: Install zsh-syntax-highlighting
  shell: >
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

- name: Add line to ~/.zshrc
  lineinfile:
    regexp: '^plugins='
    path: .zshrc
    line: 'plugins=(git zsh-autosuggestions zsh-syntax-highlighting )'
  become: yes

